@TARA.AuthenticationService.Api_HostAddress = https://localhost:10200

POST {{TARA.AuthenticationService.Api_HostAddress}}/auth/login/
Content-Type: application/json
{
  "UserName": "deinBenutzername",
  "Password": "deinPasswort"
}
###
