name: tara

services:
  tara.authenticationservice:
    image: ${DOCKER_REGISTRY-}p-bieber/tara-authenticationservice
    container_name: TARA-Authentication
    build:
      context: ../src/Services/Authentication/TARA.AuthenticationService.Api
      dockerfile: Dockerfile
  tara.db:
    image: postgres
    environment:
      POSTGRES_DB: TARAAuthenticationServiceDb
      POSTGRES_USER: yourusername
      POSTGRES_PASSWORD: yourpassword
    ports:
      - "5432:5432"
